# Generated by Django 4.2.23 on 2025-08-04 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.action')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.axis')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.level')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.project')),
            ],
            options={
                'db_table': 'planning_project_action',
                'unique_together': {('project', 'action', 'axis', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('TODO', 'A fazer'), ('DOING', 'Fazendo'), ('PENDING', 'Pendente'), ('DONE', 'Concluída')], default='TODO', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('project_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planning.projectaction')),
            ],
            options={
                'db_table': 'planning_task',
            },
        ),
        migrations.CreateModel(
            name='ProjectLevelAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.FloatField(default=0)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.axis')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.level')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.project')),
            ],
            options={
                'db_table': 'planning_project_level_axis',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='axes',
            field=models.ManyToManyField(through='planning.ProjectLevelAxis', to='planning.axis'),
        ),
        migrations.AddField(
            model_name='project',
            name='levels',
            field=models.ManyToManyField(through='planning.ProjectLevelAxis', to='planning.level'),
        ),
        migrations.AddField(
            model_name='action',
            name='axis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.axis'),
        ),
        migrations.AddField(
            model_name='action',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.level'),
        ),
    ]
