# Generated by Django 4.2.23 on 2025-09-01 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlevelaxis',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='projectaction',
            unique_together={('action', 'axis', 'level')},
        ),
        migrations.RemoveField(
            model_name='projectaction',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
