# Generated by Django 4.2.23 on 2025-07-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='projectlevelaction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='projectlevelaction',
            name='project_level',
        ),
        migrations.RemoveField(
            model_name='action',
            name='description',
        ),
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
        migrations.AddField(
            model_name='action',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.level'),
        ),
        migrations.DeleteModel(
            name='ProjectLevel',
        ),
        migrations.DeleteModel(
            name='ProjectLevelAction',
        ),
        migrations.AddField(
            model_name='task',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.action'),
        ),
        migrations.AddField(
            model_name='action',
            name='axis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.axis'),
        ),
    ]
