# Generated by Django 4.2.23 on 2025-09-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_remove_projectlevelaxis_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('url', models.URLField(verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'db_table': 'planning_paper',
            },
        ),
    ]
