# Generated by Django 4.2.23 on 2025-07-20 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_axis_task_remove_projectlevelaction_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.action'),
        ),
        migrations.CreateModel(
            name='ProjectLevelAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.FloatField()),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.axis')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.level')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='axes',
            field=models.ManyToManyField(through='planning.ProjectLevelAxis', to='planning.axis'),
        ),
        migrations.AddField(
            model_name='project',
            name='levels',
            field=models.ManyToManyField(through='planning.ProjectLevelAxis', to='planning.level'),
        ),
    ]
