# Generated by Django 4.2.23 on 2025-10-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização'),
        ),
    ]
