# Generated by Django 4.2.23 on 2025-08-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_task_action_projectlevelaxis_project_axes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.action')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.axis')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.level')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.project')),
            ],
            options={
                'unique_together': {('project', 'action', 'axis', 'level')},
            },
        ),
    ]
