BEGIN TRANSACTION;

INSERT INTO planning_paper (title, url) VALUES
('Efetividade do transporte público gratuito para inclusão de pessoas idosas (São Paulo) - Marè et al.', 'https://doi.org/10.1590/2236-9996.2024-6014'),
('Healthy Aging in Metropolitan Landscapes: Projects and Strategies to Promote the Quality of Life for Seniors - Caronte-Veisz', 'http://repositorio.ufc.br/handle/riufc/76138'),
('Urban Management in Terms of Improving Elderly People’s Life Quality - Zrałek et al.', 'https://www.um.edu.mt/library/oar/bitstream/123456789/129623/1/ERSJ27(s3)A32.pdf'),
('Age-Friendly Urban Design for Older Pedestrian Road Safety: A Street Segment Level Analysis in Madrid - Gálvez-Pérez et al.', 'https://doi.org/10.3390/su16198298'),
('Ageing with Smartphones in Urban Brazil: A Work in Progress - Duque', 'https://doi.org/10.14324/111.9781787359963'),
('An Inclusive Model for Assessing Age-Friendly Urban Environments in Vulnerable Areas - Agost-Felip et al.', 'https://www.mdpi.com/2071-1050/13/15/8352'),
('Supporting Seniors in Independent and Healthy Ageing through ICT: Insights from a Value-Focused Thinking Study in Latvia, Poland and Sweden - Soja et al.', 'https://scholarspace.manoa.hawaii.edu/items/2e3e0ece-9462-43bc-8215-3a81d0f8405b'),
('How the Responsibility of Digital Support for Older People is Allocated? The Swedish Welfare System at the Crossroads - Alexopoulou & Åström', 'https://oru.diva-portal.org/smash/get/diva2:1633461/FULLTEXT01.pdf'),
('Sustainable urban mobility analysis for elderly and disabled people in São Paulo - Azevedo et al.', 'https://doi.org/10.1038/s41598-020-80906-w'),
('Ageing in place and the built environment. Implications for the quality of life and the risks of isolation of frail older people - Sarlo et al.', 'https://www.lps.polimi.it/wp-content/uploads/2019/12/DAStU_LPS_WP06-2019.pdf'),
('Ambient Assisted Living: The case of Porto Historic Centre - Bernardo', 'https://scispace.com/papers/identity-attachment-and-roots-in-aging-4qsqxz0idq'),
('Analysing urban mobility in ageing populations: the case of two Portuguese historic centres - Ribeiro et al.', 'https://www.elgaronline.com/edcollchap-oa/edcoll/9781800370500/9781800370500.00015.xml'),
('The age-friendly attributes of Warkworth: a case study of a rural town in New Zealand - Napier', 'https://dialnet.unirioja.es/descarga/articulo/8469656.pdf'),
('A critical analysis of an IoT—aware AAL system for elderly monitoring - Almeida et al.', 'https://doi.org/10.1016/j.future.2019.03.019'),
('An Elderly Care Ecosystem Application - Baldissera et al.', 'https://dl.acm.org/doi/10.1109/IECON.2019.8927603'),
('Configurable Interactive Environment for Hybrid Knowledge- and Data-Driven Geriatric Risk Assessment - Urošević et al.', 'https://scholar.google.com.my/citations?user=d3TDBs8AAAAJ&hl=ja'),
('Determinants and Mechanisms of Improving Seniors'' Quality of Life in the ICT Ecosystem – the ActGo-Gate Project Case Study - Wroclaw University et al.', 'https://ludzie.nauka.gov.pl/ln/profiles/hZNNAVLyZmQ/publications/bf1cdd56-767f-48be-9168-f02440388e0e'),
('6G and Artificial Intelligence Technologies for Dementia Care: Literature Review and Practical Analysis - SU et al.', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9096635/'),
('Future Mobility in Alto Minho Region: Towards the path of sustainability - Baltazar et al.', 'https://doi.org/10.1109/ICE.2018.8436371'),
('How to Support the Decision-Making Process of Community Regeneration proposed by Evolutionary Game and Reinforcement Learning? A case study in Shanghai - Zhou et al.', 'https://www.mdpi.com/2075-5309/13/1/175/review_report'),
('IoT and Smart City Services to Support Independence and Wellbeing of Older People - Bryant et al.', 'http://doi.org/10.23919/SOFTCOM.2017.8115553'),
('Pedestrians'' Acceptance of Personal Mobility Devices on the Shared Path: A Structural Equation Modelling Approach - Kuo et al.', 'https://road-safety.transport.ec.europa.eu/document/download/6f698f20-f43f-4066-816a-d1db217b3bc4_en?filename=road_safety_thematic_report_personal_mobility_devices_tc_final.pdf'),
('Research on Aging-friendly Furniture Design for Public Spaces in Urban Rural Areas - Applications and Challenges in China - Zhang et al.', 'https://digital-library.theiet.org/doi/pdf/10.1049/icp.2025.0207'),
('Revealing Senior Mobility Patterns and Activities in Urban Transit Systems - Chen et al.', 'https://dl.acm.org/doi/abs/10.1109/TITS.2023.3275389'),
('Revolutionizing Malaysian Healthcare System by Harnessing the Power of IoT - Razali et al.', 'https://www.byteplus.com/en/topic/424391'),
('Shaping the digital citizen into a smart citizen on the basis of IoT capabilities - Alexandru et al.', 'https://ieeexplore.ieee.org/document/8745085'),
('SmartWalk: personas and scenarios definition and functional requirements. - Queirós et al.', 'https://nzjohng.github.io/publications/papers/ist2023_2.pdf'),
('Sustainable, assistive, residential architectural units for active ageing - Gibilisco et al.', 'https://doi.org/10.1109/MetroLivEnv56489.2023.10169397'),
('Towards Ontology-Based Requirements Engineering for IoT-Supported Well-Being, Aging and Health - Belani et al.', 'https://arxiv.org/pdf/2211.10735.pdf'),
('Viseu InterAge Stories: developing an app to foster Social Inclusion and Healthy Lifestyles - Gomes et al.', 'https://dialnet.unirioja.es/servlet/articulo?codigo=7242169'),
('Exploring the role of smart cities in supporting ageing-in-place in Chongqing, China - Woolrych et al.', 'https://onlinelibrary.wiley.com/doi/10.1111/ajag.13301'),
('Fueling the development of elderly care services in China with digital technology: A provincial panel data analysis - He et al. A', 'https://doi.org/10.1016/j.cities.2023.104019'),
('What cities have is how people travel: Conceptualizing a data-mining-driven modal split framework - Lee et al.', 'https://doi.org/10.1016/j.cities.2022.103902'),
('Decoding the spatial effects of walkability on walking behavior among older adults by integrating big data and small data - He & He', 'https://doi.org/10.1016/j.cities.2024.105537'),
('Internet use among older adults: Determinants of usage and impacts on individuals'' well-being - Shi et al.', 'https://www.sciencedirect.com/science/article/pii/S0736585322000241'),
('Crossing the digital divide: The impact of the digital economy on elderly individuals'' consumption upgrade in China - He et al. B', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11577839/'),
('Questioning the Potential for Achieving Active Ageing in Bucharest - Preda et al.', 'https://doi.org/10.24193/JSSPSI.03.PATDC'),
('Ageing in Place in Urban Environments: Critical Perspectives - Buffel & Phillipson', 'https://doi.org/10.4324/9781003229322'),
('Security Means Age-Friendliness. Analysis of Older People’s Needs Regarding the Safe Infrastructure of Open Residential Spaces. A Case Study of Poland - Czaplicka et al.', 'https://czasopisma.uwm.edu.pl/index.php/aspal/article/view/9305/7133'),
('Ageing and Urban Planning - Drilling et al.', 'https://doi.org/10.4324/9781003144441'),
('Quadruple helix collaboration for eHealth: a business relationship approach - Qvarfordt et al.', 'https://www.inderscience.com/info/inarticletoc.php?jcode=ijhtm&year=2024&vol=21&issue=2'),
('The impact of internet usage on the mental health of older adults in China: empirical analysis from a multi-dimensional perspective - Lu Wanjun', 'https://www.frontiersin.org/journals/public-health/articles/10.3389/fpubh.2024.1460558/full'),
('A Study on the Mechanisms Influencing Older Adults'' Willingness to Use Digital Displays in Museums from a Cognitive Age Perspective - Hu et al.', 'https://doi.org/10.3390/bs14061187'),
('How Can We Develop an Efficient eHealth Service for Provision of Care for Elderly People with Balance Disorders and Risk of Falling? A Mixed Methods Study - Gaspar et al.', 'https://search.ebscohost.com/login.aspx?direct=true&AuthType=ip,sso&db=rzh&AN=145944706&site=ehost-live'),
('Digitally Inclusive, Healthy Aging Communities (DIHAC): A Cross-Cultural Study in Japan, Republic of Korea, Singapore, and Thailand - Aung et al.', 'https://www.mdpi.com/1660-4601/19/12/6976'),
('Can the internet mitigate the negative effect of widowhood on Quality of Life? A gender analysis - Silva et al. B', 'https://portaberta.uminho.pt/display/cv-t-29ddfb0127734ca212e250ffcfccb8f4'),
('Seniors’ Mobility and Perceptions in Different Urban Neighbourhoods: A Non-Aggregative Approach - Burlando et al.', 'https://doi.org/10.3390/su13126647'),
('Persuasive technology to support active and healthy ageing: An exploration of past, present, and future - Cabrita et al.', 'https://doi.org/10.1016/j.jbi.2018.08.007'),
('Security and Mobility for Elderly People at Public Space and Transit - Liz et al.', 'https://dialnet.unirioja.es/descarga/articulo/8469656.pdf'),
('Exploring Social Robots for Healthy Older Adults: Aging With Companionship - Tschida et al.', ''),
('How 6G Technology Can Change the Future Wireless Healthcare - Mucchi et al.', 'https://sci-hub.ru/downloads/2020-05-16/13/mucchi2020.pdf'),
('Meet SmartWalk, Smart Cities for Active Seniors - Rodrigues et al.', 'https://scholar.google.com.br/citations?user=8i7pNc0AAAAJ&hl=pt-BR'),
('Predicting Frailty Condition in Elderly Using Multidimensional Socioclinical Databases - Bertini et al.', 'https://www.academia.edu/83238640/Predicting_Frailty_Condition_in_Elderly_Using_Multidimensional_Socioclinical_Databases'),
('Promoting livability through urban planning: A comprehensive framework based on the "theory of human needs" - Sheikh & Van Ameijde', 'https://doi.org/10.1016/j.cities.2022.103972'),
('Health Care in Cities Perceived as Smart in the Context of Population Aging—A Record from Poland - Jonek-Kowalska', 'https://doi.org/10.3390/smartcities5040065'),
('"15-Minute City" and Elderly People: Thinking about Healthy Cities - Ulloa-Leon et al.', 'https://doi.org/10.3390/smartcities6020050'),
('Social Support and "Playing Around": An Examination of How Older Adults Acquire Digital Literacy With Tablet Computers - Tsai et al.', 'https://doi.org/10.1177/0733464815609440'),
('Initiating HERMÓPOLIS Collaborative Design: Local Definitions for Building a Global Smart City Platform to Improve the Quality of Life of the Elderly - Nápoles et al.', 'https://doi.org/10.3390/urbansci9050174'),
('Leveraging Local Digital Twins for Planning Age-Friendly Urban Environments - Villanueva-Merino et al.', 'https://doi.org/10.1016/j.cities.2024.105458'),
('Trajectory tracking of changes digital divide prediction factors in the elderly through machine learning - Park Jr', 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0281291'),
('Transport, Mobility and the Wellbeing of Older Adults: An Exploration of Private Chauffeuring and Companionship Services in Malaysia - Latiff & Mohd', 'https://www.mdpi.com/1660-4601/20/3/2720'),
('A smart age-friendly city in the context of the seasonal migration of senior residents: the case of Benidorm - Labus', 'https://czasopisma.uwm.edu.pl/index.php/aspal/article/view/8438'),
('Age-Based Digital Divide: Uses of the Internet in People Over 54 Years Old - Papí-Gálvez', 'https://www.cogitatiopress.com/mediaandcommunication/article/view/6744'),
('The Paradox of Aging Population and Firm Digital Transformation in China - Wang et al.', 'https://doi.org/10.1186/s12877-024-04855-4'),
('Ten questions concerning age-friendly cities and communities and the built environment - Van Hoof et al.', 'https://doi.org/10.1016/j.buildenv.2021.107922'),
('AIoTES: Setting the principles for semantic interoperable and modern IoT-enabled reference architecture for Active and Healthy Ageing ecosystems - Valero et al.', 'https://doi.org/10.1016/j.comcom.2021.08.017'),
('Can the implementation of the smart city pilot policy improve the social adaptive health and mental health of middle-aged and elderly people? - Liu et al.', 'https://doi.org/10.1016/j.ssmph.2024.101707'),
('O idoso e a cidade: o direito a uma cidade inclusiva - Jorge', 'http://repositorio.ufc.br/handle/riufc/76138'),
('O papel da família na utilização da Internet por portugueses de 50 e mais anos: uma análise de género - Silva et al. A', 'https://doi.org/10.31447/AS00032573.2021239.06'),
('The need for an Elderly centred mobility policy - Aguiar & Macário', 'https://doi.org/10.1016/j.trpro.2017.05.309'),
('The Accidental "Age-Friendly City": Public Expectation and Subjective Experience in São Paulo - Duque & Oliveira', 'https://repositorium.sdum.uminho.pt/bitstream/1822/78574/2/2022_RLEC9.1_PT.pdf');

COMMIT;